### ISSUE TITLE
Проблема с цветопередачей при получении картинки из буфера обмена в linux

### ISSUE THREAD

**Issue by LevkinSergey** [lintest/VanessaExt#18]
OS Linux Mint 19.3
Платформа 1С 8.3.15.1700
Исходная картинка
![image](https://user-images.githubusercontent.com/36307272/75772730-8bfa4d80-5d5d-11ea-8fda-c06d35e09202.png)

То что выдает компонента
![image](https://user-images.githubusercontent.com/36307272/75772745-90bf0180-5d5d-11ea-89c6-f55f045a7637.png)

**Comment by LevkinSergey** [comment]
Такая штука во всех версиях компоненты, начиная с 08

**Comment by lintest** [comment]
Спасибо за информацию, буду разбираться

**Comment by lintest** [comment]
Можно закрывать задачу?

**Comment by LevkinSergey** [comment]
С компонентой из сегодняшнего пулреквеста все заработало. С той что в релизах-еще нет
