### ISSUE TITLE
Не работает эмуляция ввода с клавиатуры

### ISSUE THREAD

**Issue by Sv-Vik** [lintest/VanessaExt#22]
При выполнении шага:
 И в поле 'Имя поля' я ввожу текст 'Текст'
с включенным флагом  "Эмулировать ввод клавиатуры VanessaExt" текст в поле не выводится.
Если флаг снять, то текст появляется.

При этом ошибка не всегда воспроизводится, например, я сняла флаг Создавать видеоинструкции, то текст появился, обратно поставила - текст снова появился. Третий раз выполнила - текст не появился. И фокус с флагом не помог.

**Comment by lintest** [comment]
Важно чтобы фокус ввода находился в нужном элементе формы и тестируемое приложение было активным. Эмуляция производится штатными средствами Windows посредством вызова функции [**SendInput**](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput). Если активным является другой элемент формы или другое приложение, текст будет передан туда.

**Comment by Sv-Vik** [comment]
Да, спасибо! Если после выполнения сценария переключиться на браузер, то все работает.
