### ISSUE TITLE
в centos не работает снятие скринов компонентой

### ISSUE THREAD

**Issue by lintest** [lintest/VanessaExt#24]
Падает в дамп Платформа 8.3.16.1502.
Окна запущены на xfce4.

![IMG_20200813_174401_458](https://user-images.githubusercontent.com/92895/90148970-9f89f580-dd8c-11ea-923d-07c8f3951c47.jpg)

![IMG_20200813_174406_682](https://user-images.githubusercontent.com/92895/90148985-a3b61300-dd8c-11ea-9588-841d4b955c53.jpg)

**Comment by RedMammoth** [comment]
Не работает из-за различий в версиях используемых библиотек. Попробовал собрать компоненту из исходников в CentOS 7.  Ошибки нет.
Единственное исключил из сборки:
    FileFinder.cpp,
    FileFinder.h
т.к. ругается на #include <codecvt> при сборке.
И устанавливал [сторонний пакет](https://centos.pkgs.org/7/okey-x86_64/cmake3-3.12.1-2.el7.x86_64.rpm.html) для cmake3, т.к. в стандартном репозитории есть только cmake2

Попробую собрать компоненту в ubuntu, но libpng подключить статически.
![image](https://user-images.githubusercontent.com/64589646/91634984-59c06480-e9fd-11ea-83b0-fb7f0f3b5afd.png)

**Comment by lintest** [comment]
Если будешь собирать, лучше использовать ветку "template". Там новый используется шаблон.

**Comment by lintest** [comment]
Обновил ветку develop, теперь используется новый шаблон компоненты.

**Comment by RedMammoth** [comment]
С помощью ключа _--wrap_ переопределил свою функцию pow, в которой вызвал с помощью вставки ___asm__(".symver pow,pow@GLIBC_2.2.5");_ более старую версию. Компонента собралась и запустилась под cent os, но не работает:
![image](https://user-images.githubusercontent.com/64589646/94733566-a5ee2400-0370-11eb-8efe-6c125198c17c.png)
В библиотеке png перед записью/чтением выполняется проверка версии библиотеки. Судя по отладке функции png вызываются те, что определены в платформе 1с (несмотря на то, что собирал libpng статически) и возникает различие версий. В голову приходит только собирать разные версии компоненты под deb/rpm версии 1с, в одной собирать на libpng16, в другой на libpng15.

**Comment by RedMammoth** [comment]
Если быть более точным, если собрать компоненту с libpng-1.6.37, то в ubuntu работает, в centos падает с дампом, а если собрать с libpng-1.5.13, то в cent os работает, а в ubuntu падает.

**Comment by RedMammoth** [comment]
Здесь есть собранная для cent os компонента версии 1.1.9.0
https://github.com/RedMammoth/VanessaExt/raw/fix_centos/Example/Templates/VanessaExt/Ext/Template.bin

**Comment by lintest** [comment]
Специально для CentOS 7.7 подготовлена специальная версия компоненты, которая включена в поставку Vanessa Automation отдельным макетом и подключается автоматически.
