### ISSUE TITLE
Некорректное обращение к ps под Debian при завершении клиентов

### ISSUE THREAD

**Issue by nixel2007** [lintest/VanessaExt#29]
В логах CI болтается:

```
ИНФОРМАЦИЯ - Закрытие клиента тестирования.
error: process ID list syntax error

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
```

Данные о системе:
```
Nikita Gryzlov, [16.10.20 17:29]
root@582c7a8665c3:~/Desktop# uname -a
Linux 582c7a8665c3 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 GNU/Linux
root@582c7a8665c3:~/Desktop# lsb_release --a
No LSB modules are available.
Distributor ID:  Debian
Description:  Debian GNU/Linux 9.13 (stretch)
Release:  9.13
Codename:  stretch
```

VA single - develop от 16.10.2020

**Comment by nixel2007** [comment]
@Pr-mex сказал повесить сюда, но кажется, что не по адресу)

**Comment by Pr-Mex** [comment]
Да, это отсюда приехало. Вызов ПроцессОССуществуетLinux()
https://github.com/Pr-Mex/vanessa-automation/pull/979/files
@KrapivinAndrey посмотри, плиз.

**Comment by KrapivinAndrey** [comment]
Ok

**Comment by KrapivinAndrey** [comment]
@nixel2007 У меня на Debian Strerch работает. Возможно дело в старой версии ps.
Можешь попробовать поменять
```
КомандаПоиска = ПодставитьПараметрыВСтроку("ps -ef|awk '$8~""%1"" {print $2}' > %2"
```
на 
```
КомандаПоиска = ПодставитьПараметрыВСтроку("ps -Af|awk '$8~""%1"" {print $2}' > %2"
```

**Comment by nixel2007** [comment]
Докер контейнер собран только что, так что вариант со "старой" версией несколько странен. А вот какая-нибудь урезанная из-за slim - запросто.

**Comment by KrapivinAndrey** [comment]
@nixel2007 Тоже докер пробовал. Но с докер еще веселее - у меня в докер даже пакета ps не было.
Какой тег используешь?

**Comment by nixel2007** [comment]
@krapivinandrey debian:stretch-slim

**Comment by KrapivinAndrey** [comment]
@nixel2007 Залили. Можешь поверить, а то у меня не воспроизводится

**Comment by nixel2007** [comment]
Исправлено, спасибо!
