### ISSUE TITLE
Поиск фрагмента на картинке или скриншоте

### ISSUE THREAD

**Issue by lintest** [lintest/VanessaExt#31]
Функционал поиска фрагмента картинки, библиотека OpenCV
* https://docs.opencv.org/master/de/da9/tutorial_template_matching.html
* https://docs.opencv.org/master/d4/dc6/tutorial_py_template_matching.html

```bsl
Каталог = ТекущийСценарий().Каталог + "/";
ПутьБиблиотеки = Каталог + "libVanessaExtWin64.dll";
ПодключитьВнешнююКомпоненту(ПутьБиблиотеки, "VanessaExt", ТипВнешнейКомпоненты.Native);
ВнешняяКомпонента = Новый("AddIn.VanessaExt.WindowsControl");

Картинка = Новый ДвоичныеДанные(Каталог + "small.png");
Фрагмент = Новый ДвоичныеДанные(Каталог + "freg.png");
Координаты = ВнешняяКомпонента.НайтиФрагмент(Картинка, Фрагмент);
Координаты2 = ВнешняяКомпонента.НайтиНаЭкране(Фрагмент);
```

**Comment by lintest** [comment]
![image](https://user-images.githubusercontent.com/92895/99916495-88f42280-2d1b-11eb-977a-c22054e73e02.png)

**Comment by steelvan** [comment]
То, что доктор прописал.

Сделать опознавание адреса фрагмента прямо с экрана можно ?
Иначе сейчас нужно сначала сделать снимок, потом записать снимок в файл, потом записать в файл искомый фрагмент, потом выполнить поиск.

Прошу сделать аналог https://ahk-wiki.ru/imagesearch

Спасибо !

**Comment by lintest** [comment]
Поиск уже работает, можете посмотреть примеры
