### ISSUE TITLE
ВнешнееСобытие на изменение буфера обмена.

### ISSUE THREAD

**Issue by steelvan** [lintest/VanessaExt#36]
Добрый день !

У вас есть компонента для работы с буфером обмена.
Можно ли добавить в нее ВнешнееСобытие при изменении данных в буфере обмена ?
Например, как в https://infostart.ru/public/1115590/

ВключитьОповещенияБуфераОбмена
ОтключитьОповещенияБуфераОбмена

Спасибо !

**Comment by lintest** [comment]
По ссылке исходники доступны, значит можно добавить

**Comment by lintest** [comment]
![image](https://user-images.githubusercontent.com/92895/103236550-3a5b2900-4956-11eb-911c-e3de2a100788.png)

**Comment by steelvan** [comment]
gracias
