### ISSUE TITLE
В ПолучитьСнимокЭкрана() прошу добавить координаты получаемой области экрана.

### ISSUE THREAD

**Issue by steelvan** [lintest/VanessaExt#37]
Прошу добавить создание снимка экрана с указанием координат снимка.

На сайте инфостарт есть достаточно много разработок, которые позволяют сделать снимок только целого экрана.
А потом приходится запускать nconvert.exe для получения части экрана.

---

Как вариант, можно доработать метод ПолучитьСнимокЭкрана(ИксНачала, ИгрекНачала, ИксОкончания, ИгрекОкончания) который должен возвращать двоичные данные картинки области в png формате.
Или метод СохранитьСнимокЭкрана(ИксНачала, ИгрекНачала, ИксОкончания, ИгрекОкончания, ПутьСохранения) который должен сохранять снимок в файле по указанному пути.
Прошу учесть работу с двумя мониторами => должна быть возможность указывать координаты с минусом для работы со вторым монитором.

---

Предлагаю разнести функцию ПолучитьСнимокЭкрана().

ПолучитьСнимокЭкрана(0) полностью покрывается СписокДисплеев() => ПолучитьСнимокЭкрана(ИксНачала, ИгрекНачала, ИксОкончания, ИгрекОкончания)

ПолучитьСнимокЭкрана(1) полностью покрывается АктивноеОкно() => ПолучитьСнимокОкна().

Зачем дублировать ? Выйграть две строчки ? 
Но я в любом случае напишу переменную, которая будет давать понимание что это за флаг 1 для читаемости.
чСнимокТекущегоОкна = 1;
ПолучитьСнимокЭкрана(чСнимокТекущегоОкна)
Выйгрыш в строках сомнителен, дублирование методов налицо.
---

Случай применения.
Тестование отображения веб-сайта в разных обозревателях. Если делать снимок всего окна обозревателя, то включается и служебная рамка вокруг содержимого странички (адресная строка и прочее). Надо вырезать содержательную часть.
А так можно сразу брать только снимок области показа странички и сравнивать с эталоном.

Спасибо !

**Comment by steelvan** [comment]
С редактором не смог разобраться почему абзац стал жирным, извиняюсь.

**Comment by lintest** [comment]
Предлагаю сделать так:
```bsl
ВК.ПолучитьОбластьЭкрана(X, Y, W, H)
```
Параметры: слева, сверху, ширина, высота.

**Comment by lintest** [comment]
Кстати! Сейчас можно сделать снимок окна браузера при помощи вызова WebSocket, пример есть в обработке, которая идёт вместе с поставкой внешней компоненты.

**Comment by lintest** [comment]
Если два монитора, у них единая система координат. На втором мониторе координаты начинаются не с нуля, а продолжают координаты первого

**Comment by steelvan** [comment]
У меня два монитора, один из них имеет отрицательные координаты.
Даже некоторые программы из-за этого показывают свои окошки на правом мониторе.

**Comment by steelvan** [comment]
![mons](https://user-images.githubusercontent.com/46020981/101660994-d0d3b300-3a58-11eb-8565-9c52233a2e4a.png)

**Comment by steelvan** [comment]
Нажимаю выбрать цвет, а окно показывалось на правом мониторе.
Хорошо что исходники были доступны. Убрали блокировку отрицательных координат и стало нормально.

**Comment by steelvan** [comment]
Типа второй четверти в прямоугольной системе координат.

**Comment by steelvan** [comment]
ВК.ПолучитьОбластьЭкрана(X, Y, W, H)

Хорошо
Может ПолучитьОбластьРабочегоСтола(), а то все методы почти однотипно называются :)
Как вариант, лишь бы было :)

---

Page.captureScreenshot

За наводку спасибо, планирую подключить Electron для тестования веба.
Надо будет с протоколом отладки chrome devtools разобраться.
Вижу у вас уже есть наработки в этом направлении, это может быть полезно.

**Comment by lintest** [comment]
Посмотрите вот этот репозиторий: https://github.com/lintest/1ChromeVA

![image](https://user-images.githubusercontent.com/92895/101685630-0ab4b180-3a79-11eb-96d1-d03d94266739.png)

**Comment by lintest** [comment]
Готово

```bsl
ВК.ПолучитьСнимокОбласти(X, Y, W, H)
```
