### ISSUE TITLE
Парсер языка Gherkin на C++

### ISSUE THREAD

**Issue by lintest** [lintest/VanessaExt#41]
Парсер языка Gherkin на Flex и Bison:
* http://citforum.ru/operating_systems/manpages/FLEX.1.shtml
* https://ps-group.github.io/compilers/gnu_flex_doc
* http://espressocode.top/flex-fast-lexical-analyzer-generator/
* https://habr.com/ru/post/141756/
* https://ita.sibsutis.ru/sites/csc.sibsutis.ru/files/courses/trans/LabWork4.pdf

**Comment by Pr-Mex** [comment]
Нужен метод, который принимает параметры:
1. Каталог сценариев, по которому нужно строить дерево
2. Список каталогов библиотек, которые могут содержать подсценарии.
3. Список тегов исключений (если в фиче/сценарии есть тег, который есть в списке, то фича/сценарий не загружается)
4. Список тегов фильтров (если в фиче/сценарии нет тега из списка, то фича/сценарий не загружаются)


Метод возвращает структуру вида:
Каталог1
--Каталог2
----Фича1 (теги фичи, описание фичи)
------Сценарий1 (теги сценария, комментарии сценария)
--------*Группа1(ТегиГруппы, КомментарииГруппы)
----------*Группа2
------------Шаг1 (ПараметрыШага(Значение, Тип), Снипет, ТегиШага, КомментарииШага)
------------Шаг2 (ПараметрыШага(Значение, Тип), Снипет, ТегиШага, КомментарииШага)
----------*Группа3
------------*ШагПодсценарий(ПараметрыШага(Значение, Тип), Снипет, ТегиШага, КомментарииШага, ИмяФайлаФичиПодсценария)
--------------Шаг3 (ПараметрыШага(Значение, Тип), Снипет, ТегиШага, КомментарииШага)

**Comment by Pr-Mex** [comment]
Давай добавим парсинг параметров типа Дата
```Gherkin
И шаг с датой 24.01.2021
И шаг с датой 24.01.21
```

**Comment by Pr-Mex** [comment]
Давай добавим парсинг комментариев и тегов у фичи, сценария, шага.
Для каждого объекта надо добавлять массив комментариев или тегов, если они есть
```Gherkin
#ТекстКомменатрияСценария1
#ТекстКомменатрияСценария1
@ТегСценария1
@ТегСценария2
Сценарий: Мой сценарий
    #ТекстКомменатрияШага1
    #ТекстКомменатрияШага1
    @ТегЩага1
    @ТегШага2
    И шаг один
```

**Comment by lintest** [comment]
Парсер временно вынесен в отдельный в репозиторий
https://github.com/lintest/Gherkin1C
