### ISSUE TITLE
Работа с виртуальными рабочими столами под Windows

### ISSUE THREAD

**Issue by DoublesunRUS** [lintest/VanessaExt#43]
Для того чтобы запускать клиенты тестирования ВА на виртуальных рабочих столах, необходима возможность через компоненту создавать новый виртуальный рабочий стол и перемещать окно по PID на этот рабочий стол.

Есть библиотека для powershell, которая умеет это делать.
https://github.com/MScholtes/PSVirtualDesktop

Интересует реализация команд New-Desktop и Move-Window

После установки библиотеки для powershell, получить нужное действие можно выполнением команды:
(ps -pid <pid клиента тестирования>)[0].MainWindowHandle | Move-Window (New-Desktop)

**Comment by DoublesunRUS** [comment]
Еще нужны команды:
Get-DesktopFromWindow - команда которая позвонит получить desktop для текущего клиента тестирования
Remove-Desktop - команда которая позволит удалить виртуальный desktop

И нужен в каком-то виде объект Desktop, который можно было бы передавать в команды.

**Comment by lintest** [comment]
Документация: 
* https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-ivirtualdesktopmanager

**Comment by lintest** [comment]
Новые функции управления виртуальными рабочими столами (только для Windows):
* ПолучитьКоличествоРабочихСтолов (GetDesktopCount)
* ПолучитьТекущийРабочийСтол (GetCurrentDesktop)
* СоздатьРабочийСтол (CreateDesktop)
* УдалитьРабочийСтол (RemoveDesktop)
* ПереключитьРабочийСтол (GoToDesktop)
* ПолучитьРабочийСтолОкна (GetWindowDesktop)
* ПереместитьОкноНаРабочийСтол (MoveWindowToDesktop)

**Comment by lintest** [comment]
https://github.com/lintest/VanessaExt/releases/tag/1.3.0.65
