### ISSUE TITLE
В имени реквизита при разборе теряются первые буквы "Р"

### ISSUE THREAD

**Issue by andrewzola** [lintest/VanessaExt#47]
VA 1.2.036.1
win 10
8.3.18
Если включено использование парсера из компоненты VanessaExt, то в сценарии такого вида
Когда я нахожу или создаю объект "Документы.Накладная" с именем "Накладная" на дату 12.04.1961
  И я заполняю реквизиты объекта "ИмяЗадания" по таблице
    |Имя                           |Значение                 |
    |РеквизитНачинаетсяНаБуквуР    |"Это тестовый реквизит"  |
в имени реквизита при разборе теряется первая буква "Р"
т.е. имя реквизита становиться "еквизитНачинаетсяНаБуквуР"

Способ обхода: добавить апострофы вокруг значений в таблице.
   |Имя                                               |Значение                 |
    |\`РеквизитНачинаетсяНаБуквуР\`    |"Это тестовый реквизит"  |

**Comment by lintest** [comment]
Нашел ошибку, исправил
