### ISSUE TITLE
Поиск кнопки на элементе формы

### ISSUE THREAD

**Issue by lintest** [lintest/VanessaExt#50]
https://its.1c.ru/db/v8319doc#bookmark:dev:TI000001896

```bsl
ФайлРесурса = "v8res://core83/edtButtons.zip";
ВременныйФайл = ПолучитьИмяВременногоФайла();
КопироватьФайл(ФайлРесурса, ВременныйФайл);
```

Набор картинок представляет собой архив zip-формата, который содержит картинки, описание которых приводится в файле манифеста (manifest.xml), расположенной в этом же архиве (подробнее см. здесь). Картинка может относиться к одному из вариантов разрешения экрана:

* bldpi ‑ масштаб 85%;
* ldpi ‑ масштаб 100%, для мобильных устройств ‑ разрешение менее 140 dpi;
* aldpi ‑ масштаб 125%;
* mdpi ‑ масштаб 150%, для мобильных устройств ‑ разрешение от 140 до 180 dpi;
* amdpi ‑ масштаб 175%;
* hdpi ‑ масштаб 200%, для мобильных устройств ‑ разрешение от 180 до 270 dpi;
* xdpi ‑ масштаб 300%, для мобильных устройств ‑ разрешение более 270 dpi;
* udpi ‑ масштаб 400%.

Имя каждой картинки может быть любым, а соотношение между именем картинки и разрешением указывается в манифесте. Соотношение размеров картинок в архиве можно рассчитать, базируясь на размере картинки для масштаба 100%. Так, если при масштабе 100% размер картинки равен 16 точек, то можно получить следующий набор размеров картинок для разных масштабов отображения:

* bldpi: 16*0.85 = 14 точек;
* ldpi: 16*1.00 = 16 точек;
* aldpi: 16*1.25 = 20 точек;
* mdpi: 16*1.50 = 24 точки;
* amdpi: 16*1.75 = 28 точек;
* hdpi: 16*2.00 = 32 точки;
* xdpi: 16*3.00 = 48 точек;
* udpi: 16*4.00 = 64 точки.

**Comment by lintest** [comment]
```bsl
ФайлРесурса = "v8res://core83/edtButtons.zip";
ВременныйФайл = ПолучитьИмяВременногоФайла();
КопироватьФайл(ФайлРесурса, ВременныйФайл);

ОтборКартинки = Новый Соответствие;
ОтборРазмеров = Новый Соответствие;
ОтборРазмеров.Вставить(14, "bldpi");
ОтборРазмеров.Вставить(16, "ldpi");
ОтборРазмеров.Вставить(20, "aldpi");
ОтборРазмеров.Вставить(24, "mdpi");
ОтборРазмеров.Вставить(28, "amdpi");
ОтборРазмеров.Вставить(32, "hdpi");
ОтборРазмеров.Вставить(48, "xdpi");
ОтборРазмеров.Вставить(64, "udpi");
ЗначениеОтбора = ОтборРазмеров.Получить(ВысотаКартинки);
ОтборКартинки.Вставить("screenDensity", ЗначениеОтбора);

Картинка = Новый Картинка(ВременныйФайл);
УдалитьФайлы(ВременныйФайл);
ДвоичныеДанныеКартинки = Картинка.ПолучитьДвоичныеДанные(Ложь, ОтборКартинки);
```

**Comment by Pr-Mex** [comment]
Ого ты провел исследование

**Comment by lintest** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getscalefactorformonitor

GetScaleFactorForMonitor function (shellscalingapi.h)

**Comment by lintest** [comment]
Нужно вычислять масштаб для монитора

**Comment by lintest** [comment]
Новое свойство **Масштаб** и метод **ПолучитьМасштаб()** для определения масштаба экрана.
Метод может принимать идентификатор окна в качестве параметра.
Возвращает масштаб в процентах от 100 до 400.
```bsl
ОписаниеОповещения = Новый ОписаниеОповещения("ПолученМасштабЭкрана", ЭтотОбъект);
ВнешняяКомпонента.НачатьВызовПолучитьМасштаб(ОписаниеОповещения, ИдентификаторОкна);
```
