### ISSUE TITLE
Ошибка установки компоненты в веб-клиенте

### ISSUE THREAD

**Issue by marv-ua** [lintest/VanessaExt#54]
Платформа: 1С:Предприятие 8.3 (8.3.17.1549). Сервер x64. 
Браузер Хром и ИЕ
Режим: Веб-сервер (сжатие: обычное)
Приложение: Веб-клиент
Локализация: Информационная база: украинский (Украина), Сеанс: украинский (Украина)
Вариант интерфейса: Такси
НачатьУстановкуВнешнейКомпоненты(
	Новый ОписаниеОповещения("НачатьПолучениеКомпонентыЗавершениеУстановкиКомпоненты", ЭтотОбъект,
	ДополнительныеПараметры), ИмяМакетаКомпоненты()
);

Установка внешней компоненты не выполнена!
В процессе установки произошла ошибка!
Возможно, отсутствует компонента для используемого клиентского приложения

**Comment by lintest** [comment]
Внешняя компонента VanessaExt не предназначена для использования на стороне web-клиента. Разработана как составная часть инструмента тестирования прикладных решений Vanessa Automation и выполняется в режиме менеджера тестирования. Менеджеом тестирования может выступать тонкий клиент или толстый клиент. Веб-клиент не может выступать в роли менеджера тестирования.
